ppy/osu-localisation-analyser

LocalisationAnalyser.Tests/Helpers/IO/MockFile.cs
LocalisationAnalyser.Tests/Localisation/LocalisationFileTests.cs
LocalisationAnalyser/Abstractions/IO/Default/DefaultFile.cs
LocalisationAnalyser/Abstractions/IO/IFile.cs
LocalisationAnalyser/CodeFixes/AbstractLocaliseStringCodeFixProvider.cs
LocalisationAnalyser/Localisation/LocalisationFile.cs
LocalisationAnalyser/Localisation/LocalisationFile_Walker.cs
LocalisationAnalyser/Localisation/LocalisationMember.cs
LocalisationAnalyser/Localisation/LocalisationParameter.cs
LocalisationAnalyser/Localisation/SyntaxGenerators.cs
LocalisationAnalyser/LocalisationAnalyser.csproj

MSBuild.exe doesn't seem to like netstandard2.1... I'm just following this: https://github.com/dotnet/samples/tree/main/csharp/roslyn-sdk/Tutorials/MakeConst and it seems to work.

Retarget to netstandard 2.0

---

LocalisationAnalyser.Tools/Program.cs

MSBuild.exe fails on osu.Game.csproj with:
```
Z:\Repos\osu\osu.Game\Localisation\ButtonSystem.resx : error MSB3103: Invalid Resx file. ResX input is not valid. Canno
t find valid "resheader" tags for the ResX reader and writer type names. [Z:\Repos\osu\osu.Game\osu.Game.csproj]
```
Turns out that this is just due to this definition here. Rider emits the type signatures I've added for ResX files generated through it.
Note that there are other issues preventing compilation from working, but this resolves one of them.

Rewrite reader/writer types to satisfy MSBuild.exe

---

LocalisationAnalyser.Tests/Localisation/LocalisationFileTests.cs
LocalisationAnalyser.Tests/Resources/CodeFixes/InterpolatedStringWithQuotes/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/VerbatimString/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tools.Tests/LocalisationAnalyser.Tools.Tests.csproj
LocalisationAnalyser.Tools.Tests/PhpArrayElementSyntaxNodeTest.cs
LocalisationAnalyser.Tools.Tests/PhpArraySyntaxNodeTest.cs
LocalisationAnalyser.Tools.Tests/PhpStringLiteralSyntaxNodeTest.cs
LocalisationAnalyser.Tools.Tests/PhpTokeniserTest.cs
LocalisationAnalyser.Tools/LocalisationAnalyser.Tools.csproj
LocalisationAnalyser.Tools/Php/PhpArrayElementSyntaxNode.cs
LocalisationAnalyser.Tools/Php/PhpArraySyntaxNode.cs
LocalisationAnalyser.Tools/Php/PhpLiteralSyntaxNode.cs
LocalisationAnalyser.Tools/Php/PhpStringLiteralSyntaxNode.cs
LocalisationAnalyser.Tools/Php/PhpSyntaxNode.cs
LocalisationAnalyser.Tools/Php/PhpTokeniser.cs
LocalisationAnalyser.Tools/Program.cs
LocalisationAnalyser.sln
LocalisationAnalyser/Localisation/SyntaxGenerators.cs
LocalisationAnalyser/Localisation/SyntaxTemplates.cs

`dotnet localisation from-php /home/Repos/osu-web /home/Repos/osu/osu.Game/osu.Game.csproj`
The little tokeniser I wrote doesn't support the full range of PHP syntax, for example non-string keys/values, but it passes all localisation files currently in osu!web.
Notes:
1. Nested localisations are namespaced via `.` (e.g. `beatmapsets.resx`: `panel.download.direct`).
2. It doesn't change keys other than the namespacing above. Some keys contain `-` and others contain `_` - both of these remain unchanged like the rest.
3. It replaces `:text` with string format args (e.g. from `beatmaps.resx`, `Deleted by :editor :delete_time.` becomes `Deleted by {0} {1}.`.

Add tool for .php -> .resx/.cs conversion

---

LocalisationAnalyser.Tools/Program.cs

Supersedes https://github.com/ppy/osu-localisation-analyser/pull/21
In particular, to fix cases like `pt-br`, which is non-standard casing and conflicts with other projects like Roslyn (https://github.com/dotnet/roslyn/tree/main/src/Analyzers/CSharp/Analyzers/xlf) resulting in compiler errors.

Standardise language name to IETF format

---

LocalisationAnalyser.Tools/LocalisationMemberKeyEqualityComparer.cs
LocalisationAnalyser.Tools/Program.cs

Removing duplicate keys locally and printing warnings to:
* Not outright ban the warnings osu!-side.
* Have a log of warnings somewhere that could be reported to osu-web if necessary.
* Can run `dotnet run -- from-php ~/Repos/osu-web/ ~/Repos/osu-resources/osu.Game.Resources/osu.Game.Resources.csproj 2>err.log` to list just the warnings.
Also `.ToLower()`ing the keys since resx is case-insensitive.

Remove duplicate localisation keys

---

LocalisationAnalyser.Tests/CodeFixes/AbstractLocaliseStringCodeFixTests.cs
LocalisationAnalyser.Tests/CodeFixes/LocaliseClassStringCodeFixTests.cs
LocalisationAnalyser.Tests/Helpers/IO/MockPath.cs
LocalisationAnalyser.Tests/Localisation/LocalisationFileTests.cs
LocalisationAnalyser.Tests/Resources/CodeFixes/CustomPrefix/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/CustomPrefix/Fixed/Program.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/CustomPrefix/Sources/.editorconfig
LocalisationAnalyser.Tests/Resources/CodeFixes/CustomPrefix/Sources/Program.txt
LocalisationAnalyser.Tests/Verifiers/CSharpCodeFixVerifier.cs
LocalisationAnalyser.Tools/Program.cs
LocalisationAnalyser/Abstractions/IO/Default/DefaultPath.cs
LocalisationAnalyser/Abstractions/IO/IPath.cs
LocalisationAnalyser/CodeFixes/AbstractLocaliseStringCodeFixProvider.cs
LocalisationAnalyser/CodeFixes/LocaliseCommonStringCodeFixProvider.cs
LocalisationAnalyser/Localisation/LocalisationFile.cs
LocalisationAnalyser/Localisation/SyntaxGenerators.cs
README.md

Resolves https://github.com/ppy/osu-localisation-analyser/issues/28
Resolves https://github.com/ppy/osu-localisation-analyser/issues/29
For osu!, we'll move the resource files to osu-resources. This adds an editorconfig option to adjust the "prefix" value, which is currently wired to the namespace of the `Strings` class.
For osu!, this will be set to `dotnet_diagnostic.OLOC001.prefix_namespace = osu.Game.Resources.Localisation`.
It defaults to `{AssemblyName}.Localisation` as previously.
I've also added an `--output` option to the `to-resx` command, in order for the resource files to be easily uploadable to crowdin:
```
[smgi@smgi net5.0]$ ./LocalisationAnalyser.Tools to-resx /home/smgi/Repos/osu/osu.Game/osu.Game.csproj --output ~/Desktop/test
Converting all localisation files in …
```

Add analyser prefix customisation and output directory to command

---

LocalisationAnalyser.Tests/CodeFixes/AbstractLocaliseStringCodeFixTests.cs
LocalisationAnalyser.Tests/CodeFixes/LocaliseClassStringCodeFixTests.cs
LocalisationAnalyser.Tests/CodeFixes/LocaliseCommonStringCodeFixTests.cs
LocalisationAnalyser.Tests/Verifiers/CSharpCodeFixVerifier.cs
LocalisationAnalyser/CodeFixes/AbstractLocaliseStringCodeFixProvider.cs

Tested in tests and via Rider in the osu! solution.

Workaround Rider bug causing .editorconfigs to not be read

---

LocalisationAnalyser.Tools/Program.cs

Allows for the case mentioned in https://github.com/ppy/osu/issues/13530#issuecomment-864573588 to be possible. Will update osu-resources with this.

Allow parameters parsed from PHP strings to be localisable

---

LocalisationAnalyser.Tests/CodeFixes/LocaliseClassStringCodeFixTests.cs
LocalisationAnalyser.Tests/Localisation/LocalisationFileTests.cs
LocalisationAnalyser.Tests/Resources/CodeFixes/BasicString/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/CustomPrefix/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/InterpolatedString/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/InterpolatedStringWithQuotes/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/LicenseHeader/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/LicenseHeader/Fixed/Program.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/LicenseHeader/Sources/.editorconfig
LocalisationAnalyser.Tests/Resources/CodeFixes/LicenseHeader/Sources/Program.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/LongString/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/LongStringWithLimitedWordsInName/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/NestedClass/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/VerbatimString/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tools/OsuAnalyzerConfigOptions.cs
LocalisationAnalyser.Tools/Program.cs
LocalisationAnalyser/CodeFixes/AbstractLocaliseStringCodeFixProvider.cs
LocalisationAnalyser/Localisation/LocalisationFile.cs
LocalisationAnalyser/Localisation/SyntaxGenerators.cs
LocalisationAnalyser/Localisation/SyntaxTemplates.cs
LocalisationAnalyser/Utils/DocumentUtils.cs
README.md

Hard-coding the ppy license header is bad because others want to use this tool for themselves.
```
dotnet_diagnostic.OLOC001.license_header = ...
```
It's still hard-coded in the dotnet-tool because it's only supposed to be used by osu!/in connection with osu-web.

Extract license header to .editorconfig

---

LocalisationAnalyser.Tools/Program.cs

Resolves https://github.com/ppy/osu-localisation-analyser/issues/44
Broken in .NET6, which seems to no longer support `zh-CN`/`zh-TW` via `GetCultures()`: https://github.com/dotnet/msbuild/issues/7331#issuecomment-1023776992
I recommend deleting `osu.Game.Resources/Localisation/Web` before re-running this tool.

Redirect zh-CN/zh-TW aliases to zh-Hans/zh-Hant respectively

---

LocalisationAnalyser/CodeFixes/AbstractLocaliseStringCodeFixProvider.cs
LocalisationAnalyser/CodeFixes/LocaliseCommonStringCodeFixProvider.cs

Bit of a shot in the dark, especially since I can't seem to repro this. I also can't find any documentation on this attribute but I'm seeing whisperings of it around the place:
https://github.com/dotnet/roslyn/blob/41fa23e17b30659610a2b257155b688cd4f5ac9a/src/Analyzers/CSharp/CodeFixes/QualifyMemberAccess/CSharpQualifyMemberAccessCodeFixProvider.cs#L15-L16
If this doesn't work, I think the next step is to merge the two classes into one, though that doesn't look like an easy change to make.

Attempt to fix code fixes changing order randomly

---

LocalisationAnalyser.Tests/Analysers/AbstractAnalyserTests.cs
LocalisationAnalyser.Tests/Analysers/StringCanBeLocalisedAnalyserTests.cs
LocalisationAnalyser.Tests/CodeFixes/AbstractCodeFixProviderTests.cs
LocalisationAnalyser.Tests/CodeFixes/LocaliseClassStringCodeFixProviderTests.cs
LocalisationAnalyser.Tests/CodeFixes/LocaliseCommonStringCodeFixProviderTests.cs
LocalisationAnalyser.Tests/Verifiers/CSharpAnalyzerVerifier.cs
LocalisationAnalyser.Tests/Verifiers/CSharpCodeFixVerifier.cs
LocalisationAnalyser/Analysers/StringCanBeLocalisedAnalyser.cs
LocalisationAnalyser/CodeFixes/AbstractLocaliseStringCodeFixProvider.cs
LocalisationAnalyser/Localisation/LocalisationFile.cs
LocalisationAnalyser/Localisation/LocalisationFile_Walker.cs
LocalisationAnalyser/Localisation/LocalisationMember.cs
LocalisationAnalyser/Localisation/SyntaxGenerators.cs

- Adds/renames abstract test classes so other usages can derive them.
- Normalises input/output to UTF8.
- Adds more overloads for reading `LocalisationFile`s. I ended up not needing a majority of these anymore, but the most important one is the synchronous `SourceText` override.
- Adds ability to read/write xmldoc for `LocalisationMember`s separately from the "english text" (translation text).

Refactor and improve support for more situations

---

LocalisationAnalyser.Tests/Analysers/TextDoesNotMatchXmlDocAnalyserTests.cs
LocalisationAnalyser.Tests/Analysers/XmlDocDoesNotMatchTextAnalyserTests.cs
LocalisationAnalyser.Tests/CodeFixes/MakeTextMatchXmlDocCodeFixProviderTests.cs
LocalisationAnalyser.Tests/CodeFixes/MakeXmlDocMatchTextCodeFixProviderTests.cs
LocalisationAnalyser.Tests/Resources/Analysers/TextDoesNotMatchXmlDoc/Localisation/CommonStrings.txt
LocalisationAnalyser.Tests/Resources/Analysers/XmlDocDoesNotMatchText/Localisation/CommonStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/MakeTextMatchXmlDoc/Fixed/Localisation/CommonStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/MakeTextMatchXmlDoc/Sources/Localisation/CommonStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/MakeXmlDocMatchText/Fixed/Localisation/CommonStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/MakeXmlDocMatchText/Sources/Localisation/CommonStrings.txt
LocalisationAnalyser/Analysers/AbstractMemberAnalyser.cs
LocalisationAnalyser/Analysers/TextDoesNotMatchXmlDocAnalyser.cs
LocalisationAnalyser/Analysers/XmlDocDoesNotMatchTextAnalyser.cs
LocalisationAnalyser/CodeFixes/AbstractMemberCodeFixProvider.cs
LocalisationAnalyser/CodeFixes/MakeTextMatchXmlDocCodeFixProvider.cs
LocalisationAnalyser/CodeFixes/MakeXmlDocMatchTextCodeFixProvider.cs
LocalisationAnalyser/DiagnosticRules.cs

Prereqs:
Caveats: Currently only supports properties. Since methods are going to need quite a bit of implementation themselves (I think), I'm going to get this one in as an initial pass.
Resolves the first part of https://github.com/ppy/osu-localisation-analyser/issues/37
https://user-images.githubusercontent.com/1329837/171994625-b001c9cb-2181-496a-979a-192edac01b52.mp4

Add initial analyser + codefix for when xmldoc and text don't match

---

LocalisationAnalyser.Tests/CodeFixes/LocaliseClassStringCodeFixProviderTests.cs
LocalisationAnalyser.Tests/Resources/CodeFixes/SequentialCapitals/Fixed/Localisation/ProgramStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/SequentialCapitals/Fixed/Program.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/SequentialCapitals/Sources/Program.txt
LocalisationAnalyser/CodeFixes/AbstractLocaliseStringCodeFixProvider.cs

Prereqs:
As mentioned in discord, a string like `Mac OS` would turn into `mac_o_s`, which is likely not what was intended by context. This makes it `mac_os` for this case.

Improve key derivation for sequential capital letters

---

LocalisationAnalyser/Localisation/LocalisationFile.cs
LocalisationAnalyser/Localisation/LocalisationFileExtensions.cs
LocalisationAnalyser/Localisation/LocalisationFile_Walker.cs
LocalisationAnalyser/Localisation/SyntaxGenerators.cs

By splitting out references to `SyntaxGenerators`.

Resolve build warnings

---

LocalisationAnalyser.Tests/CodeFixes/Providers/LocaliseClassStringCodeFixMockProvider.cs
LocalisationAnalyser.Tests/CodeFixes/Providers/LocaliseCommonStringCodeFixMockProvider.cs
LocalisationAnalyser/CodeFixes/AbstractLocaliseStringCodeFixProvider.cs
LocalisationAnalyser/Localisation/LocalisationFile_Walker.cs
LocalisationAnalyser/Localisation/SyntaxGenerators.cs

Two issues fixed here.
1. VSCode would throw an exception saying something along the lines of `Namespace System.Web can't be found in netstandard`. Working around this by referencing `System.Net` instead, which is in CoreCLR itself and thus should always work.
2. VSCode would duplicate file contents into the file and just generally act... weird. It was due to adding files via the workspace (see inline comment).

Improve VSCode compatibility

---

LocalisationAnalyser.Tools/Program.cs

Closes #53 (kinda?)
Previously discussed on [Discord](https://discord.com/channels/188630481301012481/188630652340404224/1070954126915145749)
I noticed after two localisation update PRs on https://github.com/ppy/osu-resources that some strings from https://github.com/ppy/osu/pull/22489 weren't included.
Based on the above Discord discussion, I thought that the analyser would support that automatically, but turns out it does not.

Add localisation support for multiple namespace levels

---

LocalisationAnalyser.Tools/Program.cs

For localisation in sub-namespaces. I was going to PR on https://github.com/ppy/osu a bump for in `.config/dotnet-tools.json` when I noticed this while comparing behaviour before and after bumping.
Despite not breaking anything on Windows, I haven't tested if it breaks on macOS or Linux. Better be safe than sorry.
This was probably an oversight during my testing for #57.
Will probably need more testing on other platforms to see if it behaves correctly.

fix: remove duplicate path separator

---

LocalisationAnalyser.Tests/Resources/Analysers/TextDoesNotMatchXmlDoc/Localisation/CommonStrings.txt
LocalisationAnalyser.Tests/Resources/Analysers/XmlDocDoesNotMatchText/Localisation/CommonStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/MakeTextMatchXmlDoc/Fixed/Localisation/CommonStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/MakeTextMatchXmlDoc/Sources/Localisation/CommonStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/MakeXmlDocMatchText/Fixed/Localisation/CommonStrings.txt
LocalisationAnalyser.Tests/Resources/CodeFixes/MakeXmlDocMatchText/Sources/Localisation/CommonStrings.txt
LocalisationAnalyser/Analysers/AbstractMemberAnalyser.cs
LocalisationAnalyser/Analysers/TextDoesNotMatchXmlDocAnalyser.cs
LocalisationAnalyser/Analysers/XmlDocDoesNotMatchTextAnalyser.cs
LocalisationAnalyser/CodeFixes/AbstractMemberCodeFixProvider.cs

I'd say this pretty much closes https://github.com/ppy/osu-localisation-analyser/issues/37
It won't correctly handle cases where the arg is replaced, e.g. `"some text {wangs}"` will transfer across literally without fixing the arg to `{0}`, but it handles the most simple missed cases.
https://github.com/ppy/osu-localisation-analyser/assets/1329837/3ce1cc61-47d0-462c-b1ad-01e3e1a9895f

Add method xmldoc analyser + codefix support

---

LocalisationAnalyser.Tests/Analysers/LocalisationKeyUsedMultipleTimesInClassAnalyserTests.cs
LocalisationAnalyser.Tests/Resources/Analysers/DuplicatedLocalisationKeys/Localisation/CommonStrings.txt
LocalisationAnalyser/Analysers/LocalisationKeyUsedMultipleTimesInClassAnalyser.cs
LocalisationAnalyser/DiagnosticRules.cs

The goal here is to catch cases like https://github.com/ppy/osu/pull/27472 and https://github.com/ppy/osu/pull/28190 in an automated manner.
Have confirmed that on https://github.com/ppy/osu/commit/f9fd1b957f7bc4464e785510111d4df1facd2888 this produces the following build errors:
```
/home/dachb/Documents/opensource/osu/osu.Game/Localisation/DeleteConfirmationContentStrings.cs(30,86): error OLOC004: The localisation key 'collections' has been used multiple times in this class [/home/dachb/Documents/opensource/osu/osu.Game/osu.Game.csproj]
/home/dachb/Documents/opensource/osu/osu.Game/Localisation/DeleteConfirmationContentStrings.cs(35,81): error OLOC004: The localisation key 'collections' has been used multiple times in this class …
```

Add analyser which checks uniqueness of translation keys in a single file

---

LocalisationAnalyser.Tools.Tests/PhpStringLiteralSyntaxNodeTest.cs
LocalisationAnalyser.Tools/Php/PhpStringLiteralSyntaxNode.cs
LocalisationAnalyser.Tools/Php/PhpTokeniser.cs

Will resolve the issue pointed out in https://github.com/ppy/osu/pull/29157#issuecomment-2260709936, but making it "\n" (literal, _not_ a newline).
Implemented the full spec from https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.single
Full osu-resources diff: https://gist.github.com/smoogipoo/cd1063ba225420e5a3a32a7e9813063e

Implement PHP string escaping semantics
